# Generated by Django 3.1.5 on 2021-10-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SipNChipApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userType',
            field=models.IntegerField(default=1),
        ),
    ]
