# Generated by Django 3.2.8 on 2021-10-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SipNChipApp', '0004_alter_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfTournament', models.DateTimeField()),
                ('playersRegistered', models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL)),
                ('sponsoredBy', models.ManyToManyField(related_name='sponsors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SipNChipApp.tournament')),
            ],
        ),
    ]
