# Generated by Django 3.2.8 on 2021-11-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SipNChipApp', '0009_auto_20211102_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='scores',
            field=models.JSONField(default=dict),
        ),
    ]
