# Generated by Django 3.2.7 on 2021-11-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SipNChipApp', '0009_auto_20211103_1139'),
        ('SipNChipApp', '0010_alter_scorecard_scores'),
    ]

    operations = [
    ]
