# Generated by Django 3.2.7 on 2021-11-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SipNChipApp', '0018_auto_20211113_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
