# Generated by Django 3.2.8 on 2021-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SipNChipApp', '0016_ordernotification'),
        ('SipNChipApp', '0020_alter_drinkorder_orderedby'),
    ]

    operations = [
    ]
